/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongIdRouteImport } from './routes/song.$id'
import { Route as AuthenticatedVasterRouteImport } from './routes/_authenticated/vaster'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedRemoteRouteImport } from './routes/_authenticated/remote'
import { Route as AuthenticatedReelsRouteImport } from './routes/_authenticated/reels'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPlaylistIdRouteImport } from './routes/_authenticated/playlist.$id'
import { Route as AuthenticatedArtistIdRouteImport } from './routes/_authenticated/artist.$id'
import { Route as AuthenticatedAlbumIdRouteImport } from './routes/_authenticated/album.$id'

const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongIdRoute = SongIdRouteImport.update({
  id: '/song/$id',
  path: '/song/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVasterRoute = AuthenticatedVasterRouteImport.update({
  id: '/vaster',
  path: '/vaster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemoteRoute = AuthenticatedRemoteRouteImport.update({
  id: '/remote',
  path: '/remote',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReelsRoute = AuthenticatedReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaylistIdRoute = AuthenticatedPlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArtistIdRoute = AuthenticatedArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlbumIdRoute = AuthenticatedAlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/intro': typeof IntroRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/home': typeof AuthenticatedHomeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/remote': typeof AuthenticatedRemoteRoute
  '/search': typeof AuthenticatedSearchRoute
  '/vaster': typeof AuthenticatedVasterRoute
  '/song/$id': typeof SongIdRoute
  '/album/$id': typeof AuthenticatedAlbumIdRoute
  '/artist/$id': typeof AuthenticatedArtistIdRoute
  '/playlist/$id': typeof AuthenticatedPlaylistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/intro': typeof IntroRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/home': typeof AuthenticatedHomeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/remote': typeof AuthenticatedRemoteRoute
  '/search': typeof AuthenticatedSearchRoute
  '/vaster': typeof AuthenticatedVasterRoute
  '/song/$id': typeof SongIdRoute
  '/album/$id': typeof AuthenticatedAlbumIdRoute
  '/artist/$id': typeof AuthenticatedArtistIdRoute
  '/playlist/$id': typeof AuthenticatedPlaylistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/intro': typeof IntroRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reels': typeof AuthenticatedReelsRoute
  '/_authenticated/remote': typeof AuthenticatedRemoteRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/vaster': typeof AuthenticatedVasterRoute
  '/song/$id': typeof SongIdRoute
  '/_authenticated/album/$id': typeof AuthenticatedAlbumIdRoute
  '/_authenticated/artist/$id': typeof AuthenticatedArtistIdRoute
  '/_authenticated/playlist/$id': typeof AuthenticatedPlaylistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/intro'
    | '/admin'
    | '/browse'
    | '/home'
    | '/library'
    | '/onboarding'
    | '/profile'
    | '/reels'
    | '/remote'
    | '/search'
    | '/vaster'
    | '/song/$id'
    | '/album/$id'
    | '/artist/$id'
    | '/playlist/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/intro'
    | '/admin'
    | '/browse'
    | '/home'
    | '/library'
    | '/onboarding'
    | '/profile'
    | '/reels'
    | '/remote'
    | '/search'
    | '/vaster'
    | '/song/$id'
    | '/album/$id'
    | '/artist/$id'
    | '/playlist/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/intro'
    | '/_authenticated/admin'
    | '/_authenticated/browse'
    | '/_authenticated/home'
    | '/_authenticated/library'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/reels'
    | '/_authenticated/remote'
    | '/_authenticated/search'
    | '/_authenticated/vaster'
    | '/song/$id'
    | '/_authenticated/album/$id'
    | '/_authenticated/artist/$id'
    | '/_authenticated/playlist/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  IntroRoute: typeof IntroRoute
  SongIdRoute: typeof SongIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/song/$id': {
      id: '/song/$id'
      path: '/song/$id'
      fullPath: '/song/$id'
      preLoaderRoute: typeof SongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vaster': {
      id: '/_authenticated/vaster'
      path: '/vaster'
      fullPath: '/vaster'
      preLoaderRoute: typeof AuthenticatedVasterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remote': {
      id: '/_authenticated/remote'
      path: '/remote'
      fullPath: '/remote'
      preLoaderRoute: typeof AuthenticatedRemoteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reels': {
      id: '/_authenticated/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedReelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playlist/$id': {
      id: '/_authenticated/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof AuthenticatedPlaylistIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artist/$id': {
      id: '/_authenticated/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof AuthenticatedArtistIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/album/$id': {
      id: '/_authenticated/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AuthenticatedAlbumIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReelsRoute: typeof AuthenticatedReelsRoute
  AuthenticatedRemoteRoute: typeof AuthenticatedRemoteRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedVasterRoute: typeof AuthenticatedVasterRoute
  AuthenticatedAlbumIdRoute: typeof AuthenticatedAlbumIdRoute
  AuthenticatedArtistIdRoute: typeof AuthenticatedArtistIdRoute
  AuthenticatedPlaylistIdRoute: typeof AuthenticatedPlaylistIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReelsRoute: AuthenticatedReelsRoute,
  AuthenticatedRemoteRoute: AuthenticatedRemoteRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedVasterRoute: AuthenticatedVasterRoute,
  AuthenticatedAlbumIdRoute: AuthenticatedAlbumIdRoute,
  AuthenticatedArtistIdRoute: AuthenticatedArtistIdRoute,
  AuthenticatedPlaylistIdRoute: AuthenticatedPlaylistIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  IntroRoute: IntroRoute,
  SongIdRoute: SongIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
